#!/usr/bin/env python3
"""Generate ``docs/reference/service-map.md`` from the source AST.

This is the *generated* half of the docs: a deterministic, always-accurate map of
the service surface (file tree, public class/function signatures, HTTP routes and
the mixin assembly / MRO). The *authored* docs under ``docs/`` explain the **why**;
this file records the **what** so it can never silently drift from the code.

Usage::

    python scripts/gen_service_map.py            # (re)write the map
    python scripts/gen_service_map.py --check     # exit 1 + diff if the map is stale

The ``--check`` mode is wired into the gate (see ``.claude/skills/gate/SKILL.md``):
the build fails when the committed map no longer matches the code. The remedy is
``python scripts/gen_service_map.py && git add docs/reference/service-map.md``.

stdlib only (``ast``) — no new dependencies, no import execution.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "mm_jira_bot"
OUT = ROOT / "docs" / "reference" / "service-map.md"

# Files whose ``@app.<method>("/path")`` decorators define the HTTP surface.
ROUTE_FILES = ("web.py", "debug_admin.py")
HTTP_METHODS = {"get", "post", "put", "delete", "patch"}
# The assembled service class whose declared bases give the mixin MRO.
SERVICE_MODULE = SRC / "service" / "coordinator.py"
SERVICE_CLASS = "IncidentBotService"

HEADER = """<!--
  AUTO-GENERATED by scripts/gen_service_map.py — DO NOT EDIT BY HAND.
  Regenerate after code changes: python scripts/gen_service_map.py
  The gate (/gate) runs `--check` and fails when this file is stale.
-->

# Service map

Mechanical, generated map of the `mm_jira_bot` service surface. For the *why*
(design rationale, flows, gotchas) read the authored docs under `docs/`.
"""


def is_public(name: str) -> bool:
    return not name.startswith("_")


def line_count(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines())


def format_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Render a callable's parameter list, with annotations and defaults."""
    a = node.args
    parts: list[str] = []

    def render(arg: ast.arg, default: ast.expr | None) -> str:
        text = arg.arg
        if arg.annotation is not None:
            text += f": {ast.unparse(arg.annotation)}"
        if default is not None:
            sep = " = " if arg.annotation is not None else "="
            text += f"{sep}{ast.unparse(default)}"
        return text

    positional = list(a.posonlyargs) + list(a.args)
    # Defaults align to the tail of the positional parameters.
    pos_defaults: list[ast.expr | None] = [None] * (len(positional) - len(a.defaults))
    pos_defaults += list(a.defaults)

    for idx, arg in enumerate(positional):
        parts.append(render(arg, pos_defaults[idx]))
        if a.posonlyargs and idx == len(a.posonlyargs) - 1:
            parts.append("/")

    if a.vararg is not None:
        parts.append("*" + render(a.vararg, None))
    elif a.kwonlyargs:
        parts.append("*")

    for arg, default in zip(a.kwonlyargs, a.kw_defaults, strict=True):
        parts.append(render(arg, default))

    if a.kwarg is not None:
        parts.append("**" + render(a.kwarg, None))

    sig = "(" + ", ".join(parts) + ")"
    if node.returns is not None:
        sig += f" -> {ast.unparse(node.returns)}"
    return sig


def callable_label(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def " if isinstance(node, ast.AsyncFunctionDef) else "def "
    return f"{prefix}{node.name}{format_signature(node)}"


def collect_module(path: Path) -> dict:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    classes: list[dict] = []
    functions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and is_public(node.name):
            bases = [ast.unparse(b) for b in node.bases]
            methods = sorted(
                callable_label(m)
                for m in node.body
                if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_public(m.name)
            )
            classes.append({"name": node.name, "bases": bases, "methods": methods})
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_public(node.name):
            functions.append(callable_label(node))

    classes.sort(key=lambda c: c["name"])
    functions.sort()
    return {"classes": classes, "functions": functions}


def collect_routes() -> list[dict]:
    routes: list[dict] = []

    def process(node: ast.AST, conditional: bool) -> None:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for deco in node.decorator_list:
                route = _route_from_decorator(deco)
                if route is not None:
                    method, route_path = route
                    routes.append(
                        {
                            "method": method,
                            "path": route_path,
                            "handler": node.name,
                            "conditional": conditional,
                        }
                    )
            for child in ast.iter_child_nodes(node):
                process(child, conditional)
        elif isinstance(node, ast.If):
            # Routes registered inside an ``if settings.<flag>`` are conditional.
            for child in node.body:
                process(child, True)
            for child in node.orelse:
                process(child, True)
        else:
            for child in ast.iter_child_nodes(node):
                process(child, conditional)

    for filename in ROUTE_FILES:
        path = SRC / filename
        if path.exists():
            for child in ast.iter_child_nodes(ast.parse(path.read_text(encoding="utf-8"))):
                process(child, False)

    routes.sort(key=lambda r: (r["path"], r["method"]))
    return routes


def _route_from_decorator(deco: ast.expr) -> tuple[str, str] | None:
    if not isinstance(deco, ast.Call) or not isinstance(deco.func, ast.Attribute):
        return None
    if deco.func.attr not in HTTP_METHODS:
        return None
    if not deco.args or not isinstance(deco.args[0], ast.Constant):
        return None
    if not isinstance(deco.args[0].value, str):
        return None
    return deco.func.attr.upper(), deco.args[0].value


def collect_mro() -> list[str]:
    tree = ast.parse(SERVICE_MODULE.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == SERVICE_CLASS:
            bases = [ast.unparse(b) for b in node.bases]
            # All mixins inherit only ``object`` (cooperative), so the linearized
            # MRO is the declaration order followed by ``object``.
            return [SERVICE_CLASS, *bases, "object"]
    return [SERVICE_CLASS, "object"]


def module_key(path: Path) -> str:
    return str(path.relative_to(SRC)).replace("\\", "/")


def render() -> str:
    py_files = sorted(SRC.rglob("*.py"), key=module_key)

    lines: list[str] = [HEADER.rstrip(), ""]

    # 1. File tree with line counts.
    lines.append("## File tree (`src/mm_jira_bot/`)")
    lines.append("")
    lines.append("| Module | Lines |")
    lines.append("|---|---:|")
    for path in py_files:
        lines.append(f"| `{module_key(path)}` | {line_count(path)} |")
    lines.append("")

    # 2. Mixin assembly / MRO.
    mro = collect_mro()
    lines.append("## Service assembly (MRO)")
    lines.append("")
    lines.append(f"`{SERVICE_CLASS}` is assembled from object-only mixins; linearized MRO:")
    lines.append("")
    lines.append(" → ".join(f"`{name}`" for name in mro))
    lines.append("")

    # 3. HTTP routes.
    routes = collect_routes()
    lines.append("## HTTP routes")
    lines.append("")
    lines.append(
        "_`Conditional` reflects decorator nesting inside an `if`. The `/debug/admin/*` "
        "routes show `no` because they sit at the top of `register_debug_admin`, which "
        "`web.py` calls only when `debug_admin_enabled`._"
    )
    lines.append("")
    lines.append("| Method | Path | Handler | Conditional |")
    lines.append("|---|---|---|---|")
    for route in routes:
        flag = "yes" if route["conditional"] else "no"
        lines.append(f"| {route['method']} | `{route['path']}` | `{route['handler']}` | {flag} |")
    lines.append("")

    # 4. Public API per module.
    lines.append("## Public API by module")
    lines.append("")
    for path in py_files:
        info = collect_module(path)
        if not info["classes"] and not info["functions"]:
            continue
        lines.append(f"### `{module_key(path)}`")
        lines.append("")
        for cls in info["classes"]:
            suffix = f"({', '.join(cls['bases'])})" if cls["bases"] else ""
            lines.append(f"- **class `{cls['name']}{suffix}`**")
            for method in cls["methods"]:
                lines.append(f"  - `{method}`")
        for func in info["functions"]:
            lines.append(f"- `{func}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 with a diff if the committed map is stale (no write).",
    )
    args = parser.parse_args()

    content = render()

    if args.check:
        existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if existing != content:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"{OUT.relative_to(ROOT)} (committed)",
                tofile=f"{OUT.relative_to(ROOT)} (generated)",
            )
            sys.stdout.writelines(diff)
            print(
                f"\nservice-map is stale. Run: python scripts/gen_service_map.py "
                f"&& git add {OUT.relative_to(ROOT)}",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
